#docker run -itd --rm -e USER_NAME=你的B站账号 -e USER_PASSWORD=你的B站密码 dawnspace/bilibili-live-tools

name: bilibili_live

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  bilibili_live:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Run Container
        uses: docker://dawnspace/bilibili-live-tools:latest
        with:
          args:
            -it
            --rm
            -e USER_NAME=${{ secrets.BILIBILI_LIVE_USERNAME }}
            -e USER_PASSWORD=${{ secrets.BILIBILI_LIVE_PASSWORD }}
