#docker run -itd --rm -e USER_NAME=你的B站账号 -e USER_PASSWORD=你的B站密码 dawnspace/bilibili-live-tools

name: bilibili_live

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  bilibili_live:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: bilibili_live
    container:
      image: dawnspace/bilibili-live-tools
      env:
        USER_NAME: ${{ secrets.BILIBILI_LIVE_USERNAME }}
        USER_PASSWORD: ${{ secrets.BILIBILI_LIVE_PASSWORD }}
      options:
        --name bililivetools
        -it
        --rm
    steps:
      - name: Run task
        run: |
          echo "Start Container"
          docker start bililivetools -i
