#docker run -itd --rm -e USER_NAME=你的B站账号 -e USER_PASSWORD=你的B站密码 dawnspace/bilibili-live-tools


name: bilibili_live

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  bilibili_live:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: bilibili_live
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Dawnnnnnn/bilibili-live-tools
          ref: master
      - name: Use python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Run task
        run: |
          pip3 install --no-cache-dir -r requirements.txt
          sed -i '' 's/username =/username = ${{ secrets.BILIBILI_LIVE_USERNAME }}/g' conf/bilibili.conf
          sed -i '' 's/password =/password = ${{ secrets.BILIBILI_LIVE_PASSWORD }}/g' conf/bilibili.conf
          echo '----check1----'
          sed -i '' 's/access_key =/access_key = ${{ secrets.BILIBILI_LIVE_ACCESS_KEY }}/g' conf/bilibili.conf
          echo '----check2----'
          sed -i '' 's/cookie =/cookie = ${{ secrets.BILIBILI_LIVE_COOKIE }}/g' conf/bilibili.conf
          echo '----check3----'
          sed -i '' 's/csrf =/csrf = ${{ secrets.BILIBILI_LIVE_CSRF }}/g' conf/bilibili.conf
          echo '----check4----'
          sed -i '' 's/uid =/uid = ${{ secrets.BILIBILI_LIVE_UID }}/g' conf/bilibili.conf
          echo '----check5----'
          sed -i '' 's/refresh_token =/refresh_token = ${{ secrets.BILIBILI_LIVE_REFRESH_TOKEN }}/g' conf/bilibili.conf
          python3 ./run.py