#docker run -itd --rm -e USER_NAME=你的B站账号 -e USER_PASSWORD=你的B站密码 dawnspace/bilibili-live-tools

name: bilibili_live

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 0 16 * * *

jobs:
  bilibili_live:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: bilibili_live
    container:
      image: dawnspace/bilibili-live-tools
      env:
        USER_NAME: ${{ BILIBILI_LIVE_USERNAME }}
        PASS_WORD: ${{ BILIBILI_LIVE_PASSWORD }}
      options:
        -itd
        --rm
    steps:
      - name: Run task
        run: |
          echo "Run task"
