#docker run -itd --rm -e USER_NAME=你的B站账号 -e USER_PASSWORD=你的B站密码 dawnspace/bilibili-live-tools

name: bilibili_live

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  bilibili_live:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: bilibili_live
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Dawnnnnnn/bilibili-live-tools
          ref: master
      - name: Use python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Run task
        run: |
          ls -lha
          pip3 install --no-cache-dir -r requirements.txt
          sed -i ''"$(cat conf/bilibili.conf -n | grep "username =" | awk '{print $1}')"'c '"$(echo "username = ${{ secrets.BILIBILI_LIVE_USERNAME }}")"'' conf/bilibili.conf
          sed -i ''"$(cat conf/bilibili.conf -n | grep "password =" | awk '{print $1}')"'c '"$(echo "password = ${{ secrets.BILIBILI_LIVE_PASSWORD}}")"'' conf/bilibili.conf
          python ./run.py