name: 'ff14'

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
     - uses: actions/checkout@v2
     - name: 'setup python'
       uses: actions/setup-python@master
       with:
        python-version: 3.7
        
     - name: 'setup env'
       uses: actions/checkout@v2
       with:
          repository: mengshouer/CheckinBox
          ref: master
        
     - name: list
       run: ls
     
     - name: requirements
       run : pip3 install -r requirements.txt

     - name: main
       env:
         SCKEY: ${{ secrets.SCKEY }}
         fflogin_name: ${{ secrets.fflogin_name }}
         fflogin_password: ${{ secrets.fflogin_password }}
         area_name: ${{ secrets.area_name }}
         server_name: ${{ secrets.server_name }}
         role_name: ${{ secrets.role_name }}
       run: |
         python3 ./FF14Checkin/FF14CheckinForSCF.py
