name: smzdm

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: fashionzzZ/sign-actions

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm install

      - name: Run app
        run: node smzdm.js
        env:
          SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
