name: v2ex

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          repository: fashionzzZ/sign-actions

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm install

      - name: Run app
        run: node v2ex.js
        env:
          V2EXCK: ${{ secrets.V2EX_COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
